# -*- coding: utf-8 -*-
"""week_2_assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EWhhmL3YPzpFQPxCOj9qc3VxmftPmaoZ
"""

def avg(data):
    prices = []
    for key in data.keys():
        for item in data[key]:
            prices.append(item['price'])
    return round((sum(prices)/len(prices)),3)

print(     
    avg(
        {
            "products": 
                [
                    {                 
                        "name": "Product 1",
                        "price": 100
                    },             
                    {                 
                        "name": "Product 2",
                        "price": 700             
                    },             
                    {                 
                        "name": "Product 3",
                        "price": 300             
                    }
                ]
        }
    )
) # print the average price of all products (round to 3 decimal)