# -*- coding: utf-8 -*-
"""week_2_assignment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GnmGPdEslQEBTvCwqkfgh2DODl9PFWBA
"""

def count(input): 
    key = list(set(input))
    key.sort()
    value = [input.count(i) for i in key]
    result = dict(zip(key,value))
    return result

input1 = ['a', 'b', 'c', 'a', 'c', 'a', 'x'] 
print(count(input1)) 
# should print {'a': 3, 'b': 1, 'c': 2, 'x': 1}


def group_by_key(input): 
    result = {}
    for item in input:
        if item['key'] in result.keys():
            result[item['key']] += item['value']
        else:
            result[item['key']] = item['value']
    return result


input2 = [     
          {'key': 'a', 'value': 3},
          {'key': 'b', 'value': 1},
          {'key': 'c', 'value': 2},
          {'key': 'a', 'value': 3},
          {'key': 'c', 'value': 5} ] 

print(group_by_key(input2)) 
# should print {‘a’: 6, ‘b’: 1, ‘c’: 7}